openapi: 3.0.3

info:
  version: 0.0.1
  title: Reservation API

paths:
  /:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponseModel"

components:
  schemas:
    DefaultResponseModel:
      type: object
      properties:
        message:
          type: string
      required:
        - message
