openapi: 3.0.3

info:
  version: 0.0.1
  title: Reservation API

paths:
  /api:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponseModel"
  /api/auth/csrf:
    get:
      operationId: GetCsrfToken
      tags:
        - auth
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CSRFModel"

components:
  schemas:
    DefaultResponseModel:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    CSRFModel:
      type: object
      properties:
        csrf:
          type: string
      required:
        - csrf
